### PR TITLE
App Install Location

### PR DESCRIPTION
**Pull request by SweetLion**
The internal memory of my device is quite small, this PR should allow users to easily move the app to the microSD.

"To allow the system to install your application on the external storage, modify your manifest file to include the android:installLocation attribute in the element, with a value of either "preferExternal" or "auto"." (source: https://developer.android.com/guide/topics/data/install-location.html)

Thank you very much for your awesome app :)

### CODE REVIEW

**Comment by L-Henke** [comment]
I have no way to test this PR because all my devices have internal memory only. But it definitely looks sane.

By the way, you say that your device has a small internal memory so I just assume that the device isn't very powerful at all. If that is true, does secrecy perform well on such a device? I only have quite powerful devices to test the app.

**Comment by SweetLion** [comment]
Hi @L-Henke, I could test it if you send me the APK. I am using a Samsung Galaxy Xcover (first generation) and Secrecy works OK (in fact, all apps are bit laggy).

**Comment by Doplgangr** [comment]
I'm just curious, how do you set the install location? can you choose it during install or is it done automatically?

**Comment by SweetLion** [comment]
Using android:installLocation="auto" the system decides automatically where to install the app. When the internal storage is full the system installs it externally otherwise internally. 

android:installLocation="preferExternal" prefers the external storage and uses the internal storage only if no external storage is available or the microSD is full. Big games use this setting. 

With both options it is possible to change the install location manually in the settings (settings --> apps). You can find it where you can uninstall the apps too.

move-flash-player-to-sdcard-apps2sd

Thank you very much for your support and interest. :+1: 
I will write again if I experience unexpected behaviour of the app on my microSD.

**Comment by SweetLion** [comment]
Can you please send me the APK to test it on my device?

**Pull request merged**
