### PR TITLE
Added listener for keyboard on unlocking vault.

### PR DESCRIPTION
**Pull request by vixsomnis**
Created a "PasswordListener" class for listening for both the "ok button" and the "done" key (IME_ACTION_DONE). The original code used for retrieving the input is unchanged, just moved into the new listener.  Further work is necessary, as this doesn't work with the OnLongClickListener for renaming the vault yet.

Also, added some gitignore entries (vim swap files, error logs).  I sorted them, hence the number of changes.

Tested on Android 5.0.2 and 4.4.4. Seems to work as expected.

### CODE REVIEW

**Comment by vixsomnis** [comment]
Is there a specific reason why everything was done using anonymous inner classes? It seems to duplicate functionality in a few places, without any benefits.

**Comment by Doplgangr** [comment]
I am wondering-
does this PR aims to improve in a specific aspect? like code readability / performance / compliance to some sort of standard / bug fix?

I wonder if I've missed the reason this PR is requested, please state more clearly to let us know! :)

P.S. You may want to split the gitignore into a separate commit.

**Comment by vixsomnis** [comment]
Oh, yeah, the PR is so you can press "done"/"enter" on the keyboard when typing in the password. That way you don't have to hit the checkmark button manually to open the vault.

And about all of the nested listeners -- would it be okay for me to work on fixing those? I've heard that anonymous inner classes might have some security benefits (prevents reuse), but the current code seems overcomplicated.

I'll try to split the gitignore into a separate PR.

**Comment by Graveen** [comment]
Ah interesting, this is something i had on my TODO list for Secrecy :)

**Comment by vixsomnis** [comment]
Alright, changes are done. Let me know if there's anything else.

**Comment by Doplgangr** [comment]
works well on both of my devices
nexus4 on 5.0 and blackberry

**Pull request merged**
