### PR TITLE
[READY FOR TESTING] Removed Android Annotations

### PR DESCRIPTION
**Pull request by L-Henke**
This is massively work in progress and has a lot of rough edges, but it is compilable without Android Annotations and even ~~some~~ most(?) parts of the app are running correctly :-)

~~I'll continue tomorrow or the next days, but maybe you @Doplgangr would want to have a first look.~~

### CODE REVIEW

**Comment by L-Henke** [comment]
This PR is ready for testing. We need to test _EVERYTHING_, since all activities and fragments have been modified. I tried to adapt all Android Annotation magic into the normal Android way of doing things. I tried to be as close to the original behavior without trying to optimize too much things. Cleaning and optimizing our code base would be one of the next tasks.

There still is an issue with the version detection in the UpdateManager. I'll have a look at that.

**Comment by Doplgangr** [comment]
Thanks.
I'll be testing this build head to toe. I'll report back when I'm done.

**Comment by L-Henke** [comment]
Problem with the UpdateManager should have been fixed with 937c6bd. The used strings were not matching.

**Comment by L-Henke** [comment]
Launching via telephone does not work: ```Caused by: android.content.ActivityNotFoundException: Unable to find explicit activity class {com.doplgangr.secrecy/com.doplgangr.secrecy.views.MainActivity}; have you declared this activity in your AndroidManifest.xml?```

I am pretty sure that the MainActivity is declared, so I currently don't know what causes that. (I have also tried to add the LauncherActivity again.)

**Comment by Doplgangr** [comment]
Yes, the LauncherActivity should be the key here.

It is because by "disabling" an app, the entire activity with "app launch intent" becomes inaccessible, practically rendering the app useless if you set the "app launch intent" to MainActivity.

Thus I have introduced LauncherActivity which acts as the entry point for app launcher to handle "click on app icon" event. Even if we "disable" the app and make LauncherActivity inaccessible, the app can still enter MainActivity.

**Pull request merged**
