### PR TITLE
Renamed anim folder to animator

### PR DESCRIPTION
**Pull request by L-Henke**
Fixup for 81051c6.
Since getSupportFragmentManager has been replaced with
getFragmentManager, anim folder has to be renamed to animator or
animations can not be found.

### CODE REVIEW

**Comment by L-Henke** [comment]
To clarify this: PR #116 is broken and the app crashed on start. Normally I test all branches before merging them, but now I relied an Travis, because everything was buildable and I didn't saw any possible errors. 
I'll continue to do a basic test for all branches in the future.

**Comment by StelianMorariu** [comment]
I'll be more careful next time. :(

**Comment by L-Henke** [comment]
Not your fault. I should have tested before merging it. Mistakes happen. See #123 :)

**Comment by Doplgangr** [comment]
Yea sometimes I rely on gut instincts too and mistakes happen.

I looked at #123 and I was like "yea, that makes sense" and pushed the
merge button without hesitation.

I'll be testing everything too in future merges.

**Comment by StelianMorariu** [comment]
I get `RuntimeException: Unknown animator name: alpha` when trying to run the app in a Genymotion emulator.

**Comment by L-Henke** [comment]
Thats the exception I got before this fix. Maybe you should run ```gradle clean``` and compile it again.

**Comment by L-Henke** [comment]
Since the animators does not work with the native FragmentManager, I just removed all custom animations. I think this is quicker now than figuring out how to adapt them. We can re-add them later if someone is willing to adapt the animations.

**Comment by Doplgangr** [comment]
Sure. Amins are just non-essential components

**Comment by StelianMorariu** [comment]
The app is starting, can open vault, can open picture from vault.
It looks good.

**Comment by StelianMorariu** [comment]
Sorry if I'm stepping on your toes, but master is broken and it's difficult to create new PR without this merge

**Pull request merged**
