### PR TITLE
Added sort by filetype

### PR DESCRIPTION
**Pull request by L-Henke**
This PR allows to either sort files by name or group them by file type and order by name in the groups.
It also a base for more sorting options since the binary CheckboxPreference has been replaced with a ListPreference.

### CODE REVIEW

**Comment by Doplgangr** [comment]
1. Conflict.
2. I'm thinking that owing to the massive changes we are undergoing, is this version code bump legitimate for a 6.0 instead of 5.4. It would be nice too, if we could figure out a better way to do the version code so that it makes more sense for us and for the users alike.

(In the past, I just base version changes on the degree of changes I have made. For example if there is any big UI improvement and/or feature inclusion, it would be a digit increment. If just bug fixes and small UI changes, it would be a .1 increment.)

**Comment by L-Henke** [comment]
Rebased and version bumped to 0.6.0

**Comment by L-Henke** [comment]
@Doplgangr 
The best practice is semantic versioning: http://semver.org/. I think I already said that we should use that.

**Comment by StelianMorariu** [comment]
Semantic versioning sound good to me.

**Comment by Doplgangr** [comment]
Ah thanks for the reminder.

**Pull request merged**
