### PR TITLE
Added SCREEN_OFF listener service

### PR DESCRIPTION
**Pull request by L-Henke**
I tried to extract the relevant changes from #129.

@StelianMorariu I committed in your name, because these are your changes. Please tell me if that are all relevant changes. If your PR would have looked like this, I would have merged it pretty fast.

### CODE REVIEW

**Comment by StelianMorariu** [comment]
Hi,
The PR has the relevant changes. Sorry for the lack of activity :( I'll try to get back on track ASAP.

**Comment by L-Henke** [comment]
But it doesn't work at the moment. I'm trying to fix that. And you don't have to be sorry for the lack of activity, we are all only working on this when we have free time ;)

**Comment by L-Henke** [comment]
If I put this into the FilePhotoFragment:
```
    public void onEventMainThread(ScreenOffEvent event) {
        Util.log("FilePhotoFragment : Recieving screen of event");
        finish();
    }
```
It should receive the screen of event, but it does not although the ```ImageLoadDoneEvent``` in the same activity can be received. This either is a bug in EventBus, or I'm missing something...
It just logs: ```No subscribers registered for event class com.doplgangr.secrecy.events.ScreenOffEvent``` (after I have removed the code from the ```FilesActivity```)

**Comment by StelianMorariu** [comment]
If I remember correctly, that was the same dead end I reached. I know the old PR I created didn't have the event in `FilePhotoFragment` because I was still trying to fix it.  I couldn't figure it out....

**Comment by Graveen** [comment]
Re,
Actually going into screen off mode is not closing secrecy, both on 4.2.2 or 5.1, seems to be a regression, @L-Henke do you have an idea where it stands ?

**Comment by L-Henke** [comment]
I currently don't have much time to investigate on this, in about three weeks I'll have more time again for development.

**Comment by Doplgangr** [comment]
I'm heading to mainland China where no gmailing is possible. I'll be on this issue when I'm back

**Comment by Doplgangr** [comment]
I think I've got the problem.

There are 2 classes in the project, one ```FilePhotoFragment``` and one ```FilePhotoActivity```, where the ```FilePhotoFragment``` is actually a FragmentActivity.

```FilePhotoFragment``` has been orphaned (I did a simple Find Usage search and it showed no usage in project files)

Thus if you add the relevant changes to ```FilePhotoFragment``` it would not work because the ```FilePhotoActivity``` is used instead.

I suspect this is a problem resulted from the refractoring effort. ```FilePhotoActivity``` is much simpler than ```FilePhotoFragment```, maybe we should move the contents from ```FilePhotoFragment``` to ```FilePhotoActivity``` and remove it.

**Comment by Doplgangr** [comment]
Just verified the speculation. The activity closes if you move your code to ```FilePhotoActivity```.

**Comment by Graveen** [comment]
Worth to be committed :)

**Pull request merged**
