### PR TITLE
Min SDK

### PR DESCRIPTION
**Pull request by StelianMorariu**
PR based on #113  that :
* increases the minimum SDK version to 14
* updates all fragments and activities to use android.app.Fragment
* remove unnecessary library (PreferenceFragment)

### CODE REVIEW

**Comment by L-Henke** [comment]
That actually is a good reason.
If this PR would have been base on the master, I would probably merge it after a short test. But since this also includes #113, I'll wait with it because I'd like to hear a word on #113 from @Doplgangr.

**Comment by L-Henke** [comment]
I know that I'm nitpicking. Except for the unclean reverted commit, this PR should be ready to merge.

**Comment by L-Henke** [comment]
Since I manually merged #113 into the master without e7281a5 and a585b56, you have to rebase this PR onto the current master:
```
git checkout master
git pull upstream master
git checkout min_sdk
git rebase master
git push origin -f
```
(Command just in case)

**Comment by StelianMorariu** [comment]
@L-Henke  thanks for the commands, I'm a not so good with Git

**Comment by StelianMorariu** [comment]
@L-Henke  thanks for the commands, I'm not so good with Git.

**Comment by Doplgangr** [comment]
I looked into the recent activities and all seemed fine for me. The swift jump of SDK version really allows a better freedom in development and I'd love that. 
(Currently it seems like there is no really serious bugs in the production version, so that those left out by the SDK version would most likely continue using the old version without too much problem.)

P.S.Sorry for being left out, I've been working on an upcoming exam but I'll be right back.

**Pull request merged**
