### PR TITLE
Changed rename and password input handling

### PR DESCRIPTION
**Pull request by vixsomnis**
Replaced anonymous listeners with an OOP design. Added "done" keyboard
button responsiveness to name entry and nested password entry.

### CODE REVIEW

**Comment by vixsomnis** [comment]
To clarify, this is a continuation of commit 70a8c58aaed6cd5ed3f0bb0fe2cf778c6c3e3ba7. The feature has been extended to the rename interface and the code has been simplified.

**Comment by L-Henke** [comment]
Works on my device and technically looks ok. The code style is sometimes a little bit weird e.g. some very pessimistic line breaks (https://github.com/SecrecySupportTeam/secrecy/pull/145/files#diff-53fe7d734d7776056da77b8de024cce1R442) and in-line comments are below the belonging code line and are using a different indentation. A commenting style I've never seen before anywhere...

**Comment by L-Henke** [comment]
Currently it is not mergeable, probable due to the unnecessary commit 920ffe0.

**Comment by vixsomnis** [comment]
Sorry about the strange style (why I wanted to check if there were any agreed upon standards). Once we have the contributing document worked out, I'll try to fix the code I touched to match it.

**Comment by L-Henke** [comment]
Its not a big deal since we really don't have a consistent style.

**Comment by L-Henke** [comment]
...yet!

**Comment by L-Henke** [comment]
Looks fine for me. @Doplgangr you might want to have a look. Otherwise just merge it at your will.

**Comment by Doplgangr** [comment]
We'd probably create a centralized document on coding style and work from there

**Pull request merged**
